services:
  - type: web
    name: my-selenium-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      apt-get update && apt-get install -y chromium-browser && python app.py
